 
 
 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using  OData2Poco Class library.
//     Service Url: http://services.odata.org/V4/OData/OData.svc
//     MetaData Version: 4.0
//     Generated On: 2019-03-04T03:19:43
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataDemo
{
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.Spatial;

	public partial class Product
	{
	    [Key]
	    public virtual int ID {get;set;} //PrimaryKey not null

	    public virtual string Name {get;set;} 

	    public virtual string Description {get;set;} 

	    public virtual DateTimeOffset ReleaseDate {get;set;} // not null

	    public virtual DateTimeOffset? DiscontinuedDate {get;set;} 

	    public virtual short Rating {get;set;} // not null

	    public virtual double Price {get;set;} // not null

	    public virtual List<Category> Categories {get;set;} 

	    public virtual Supplier Supplier {get;set;} 

	    public virtual ProductDetail ProductDetail {get;set;} 

	}

	public partial class FeaturedProduct : Product
	{
	    public virtual Advertisement Advertisement {get;set;} 

	}

	public partial class ProductDetail
	{
	    [Key]
	    public virtual int ProductID {get;set;} //PrimaryKey not null

	    public virtual string Details {get;set;} 

	    public virtual Product Product {get;set;} 

	}

	public partial class Category
	{
	    [Key]
	    public virtual int ID {get;set;} //PrimaryKey not null

	    public virtual string Name {get;set;} 

	    public virtual List<Product> Products {get;set;} 

	}

	public partial class Supplier
	{
	    [Key]
	    public virtual int ID {get;set;} //PrimaryKey not null

	    public virtual string Name {get;set;} 

	    public virtual Address Address {get;set;} 

	    public virtual GeographyPoint Location {get;set;} 

	    public virtual int Concurrency {get;set;} // not null

	    public virtual List<Product> Products {get;set;} 

	}

	public partial class Address
	{
	    public virtual string Street {get;set;} 

	    public virtual string City {get;set;} 

	    public virtual string State {get;set;} 

	    public virtual string ZipCode {get;set;} 

	    public virtual string Country {get;set;} 

	}

	public partial class Person
	{
	    [Key]
	    public virtual int ID {get;set;} //PrimaryKey not null

	    public virtual string Name {get;set;} 

	    public virtual PersonDetail PersonDetail {get;set;} 

	}

	public partial class Customer : Person
	{
	    public virtual decimal TotalExpense {get;set;} // not null

	}

	public partial class Employee : Person
	{
	    public virtual long EmployeeID {get;set;} // not null

	    public virtual DateTimeOffset HireDate {get;set;} // not null

	    public virtual float Salary {get;set;} // not null

	}

	public partial class PersonDetail
	{
	    [Key]
	    public virtual int PersonID {get;set;} //PrimaryKey not null

	    public virtual byte Age {get;set;} // not null

	    public virtual bool Gender {get;set;} // not null

	    public virtual string Phone {get;set;} 

	    public virtual Address Address {get;set;} 

	    public virtual Stream Photo {get;set;} // not null

	    public virtual Person Person {get;set;} 

	}

	public partial class Advertisement
	{
	    [Key]
	    public virtual Guid ID {get;set;} //PrimaryKey not null

	    public virtual string Name {get;set;} 

	    public virtual DateTimeOffset AirDate {get;set;} // not null

	    public virtual FeaturedProduct FeaturedProduct {get;set;} 

	}

}
  