#if x
vb code 
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations.Schema
Imports System.IO
Imports System.Spatial

'uncomment for spatial data type and run Install-Package System.Spatial 
'using System.Spatial;
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated using  OData2Poco Class library.
'     Service Url: data\northwindV4.xml
'     MetaData Version: 4.0
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ODataDemo
	<Table("Products")> _
	Public Class Product
		Public Property ID() As Integer
			Get
				Return m_ID
			End Get
			Set
				m_ID = Value
			End Set
		End Property
		Private m_ID As Integer
		' //PrimaryKey not null
		Public Property Name() As String
			Get
				Return m_Name
			End Get
			Set
				m_Name = Value
			End Set
		End Property
		Private m_Name As String
		Public Property Description() As String
			Get
				Return m_Description
			End Get
			Set
				m_Description = Value
			End Set
		End Property
		Private m_Description As String
		Public Property ReleaseDate() As DateTimeOffset
			Get
				Return m_ReleaseDate
			End Get
			Set
				m_ReleaseDate = Value
			End Set
		End Property
		Private m_ReleaseDate As DateTimeOffset
		' // not null
		Public Property DiscontinuedDate() As DateTimeOffset
			Get
				Return m_DiscontinuedDate
			End Get
			Set
				m_DiscontinuedDate = Value
			End Set
		End Property
		Private m_DiscontinuedDate As DateTimeOffset
		Public Property Rating() As Short
			Get
				Return m_Rating
			End Get
			Set
				m_Rating = Value
			End Set
		End Property
		Private m_Rating As Short
		' // not null
		Public Property Price() As Double
			Get
				Return m_Price
			End Get
			Set
				m_Price = Value
			End Set
		End Property
		Private m_Price As Double
		' // not null
	End Class

	Public Class FeaturedProduct
		Public Property ID() As Integer
			Get
				Return m_ID
			End Get
			Set
				m_ID = Value
			End Set
		End Property
		Private m_ID As Integer
		' // not null
		Public Property Name() As String
			Get
				Return m_Name
			End Get
			Set
				m_Name = Value
			End Set
		End Property
		Private m_Name As String
		Public Property Description() As String
			Get
				Return m_Description
			End Get
			Set
				m_Description = Value
			End Set
		End Property
		Private m_Description As String
		Public Property ReleaseDate() As DateTimeOffset
			Get
				Return m_ReleaseDate
			End Get
			Set
				m_ReleaseDate = Value
			End Set
		End Property
		Private m_ReleaseDate As DateTimeOffset
		' // not null
		Public Property DiscontinuedDate() As DateTimeOffset
			Get
				Return m_DiscontinuedDate
			End Get
			Set
				m_DiscontinuedDate = Value
			End Set
		End Property
		Private m_DiscontinuedDate As DateTimeOffset
		Public Property Rating() As Short
			Get
				Return m_Rating
			End Get
			Set
				m_Rating = Value
			End Set
		End Property
		Private m_Rating As Short
		' // not null
		Public Property Price() As Double
			Get
				Return m_Price
			End Get
			Set
				m_Price = Value
			End Set
		End Property
		Private m_Price As Double
		' // not null
		Public Property Categories() As List(Of Category)
			Get
				Return m_Categories
			End Get
			Set
				m_Categories = Value
			End Set
		End Property
		Private m_Categories As List(Of Category)
		Public Property Supplier() As Supplier
			Get
				Return m_Supplier
			End Get
			Set
				m_Supplier = Value
			End Set
		End Property
		Private m_Supplier As Supplier
		Public Property ProductDetail() As ProductDetail
			Get
				Return m_ProductDetail
			End Get
			Set
				m_ProductDetail = Value
			End Set
		End Property
		Private m_ProductDetail As ProductDetail
	End Class

	<Table("ProductDetails")> _
	Public Class ProductDetail
		Public Property ProductID() As Integer
			Get
				Return m_ProductID
			End Get
			Set
				m_ProductID = Value
			End Set
		End Property
		Private m_ProductID As Integer
		' //PrimaryKey not null
		Public Property Details() As String
			Get
				Return m_Details
			End Get
			Set
				m_Details = Value
			End Set
		End Property
		Private m_Details As String
	End Class

	<Table("Categories")> _
	Public Class Category
		Public Property ID() As Integer
			Get
				Return m_ID
			End Get
			Set
				m_ID = Value
			End Set
		End Property
		Private m_ID As Integer
		' //PrimaryKey not null
		Public Property Name() As String
			Get
				Return m_Name
			End Get
			Set
				m_Name = Value
			End Set
		End Property
		Private m_Name As String
	End Class

	<Table("Suppliers")> _
	Public Class Supplier
		Public Property ID() As Integer
			Get
				Return m_ID
			End Get
			Set
				m_ID = Value
			End Set
		End Property
		Private m_ID As Integer
		' //PrimaryKey not null
		Public Property Name() As String
			Get
				Return m_Name
			End Get
			Set
				m_Name = Value
			End Set
		End Property
		Private m_Name As String
		Public Property Address() As Address
			Get
				Return m_Address
			End Get
			Set
				m_Address = Value
			End Set
		End Property
		Private m_Address As Address
		Public Property Location() As GeographyPoint
			Get
				Return m_Location
			End Get
			Set
				m_Location = Value
			End Set
		End Property
		Private m_Location As GeographyPoint
		Public Property Concurrency() As Integer
			Get
				Return m_Concurrency
			End Get
			Set
				m_Concurrency = Value
			End Set
		End Property
		Private m_Concurrency As Integer
		' // not null
	End Class

	Public Class Address
		Public Property Street() As String
			Get
				Return m_Street
			End Get
			Set
				m_Street = Value
			End Set
		End Property
		Private m_Street As String
		Public Property City() As String
			Get
				Return m_City
			End Get
			Set
				m_City = Value
			End Set
		End Property
		Private m_City As String
		Public Property State() As String
			Get
				Return m_State
			End Get
			Set
				m_State = Value
			End Set
		End Property
		Private m_State As String
		Public Property ZipCode() As String
			Get
				Return m_ZipCode
			End Get
			Set
				m_ZipCode = Value
			End Set
		End Property
		Private m_ZipCode As String
		Public Property Country() As String
			Get
				Return m_Country
			End Get
			Set
				m_Country = Value
			End Set
		End Property
		Private m_Country As String
	End Class

	<Table("Persons")> _
	Public Class Person
		Public Property ID() As Integer
			Get
				Return m_ID
			End Get
			Set
				m_ID = Value
			End Set
		End Property
		Private m_ID As Integer
		' //PrimaryKey not null
		Public Property Name() As String
			Get
				Return m_Name
			End Get
			Set
				m_Name = Value
			End Set
		End Property
		Private m_Name As String
	End Class

	Public Class Customer
		Public Property ID() As Integer
			Get
				Return m_ID
			End Get
			Set
				m_ID = Value
			End Set
		End Property
		Private m_ID As Integer
		' // not null
		Public Property Name() As String
			Get
				Return m_Name
			End Get
			Set
				m_Name = Value
			End Set
		End Property
		Private m_Name As String
		Public Property PersonDetail() As PersonDetail
			Get
				Return m_PersonDetail
			End Get
			Set
				m_PersonDetail = Value
			End Set
		End Property
		Private m_PersonDetail As PersonDetail
		Public Property TotalExpense() As Decimal
			Get
				Return m_TotalExpense
			End Get
			Set
				m_TotalExpense = Value
			End Set
		End Property
		Private m_TotalExpense As Decimal
		' // not null
	End Class

	Public Class Employee
		Public Property ID() As Integer
			Get
				Return m_ID
			End Get
			Set
				m_ID = Value
			End Set
		End Property
		Private m_ID As Integer
		' // not null
		Public Property Name() As String
			Get
				Return m_Name
			End Get
			Set
				m_Name = Value
			End Set
		End Property
		Private m_Name As String
		Public Property PersonDetail() As PersonDetail
			Get
				Return m_PersonDetail
			End Get
			Set
				m_PersonDetail = Value
			End Set
		End Property
		Private m_PersonDetail As PersonDetail
		Public Property EmployeeID() As Long
			Get
				Return m_EmployeeID
			End Get
			Set
				m_EmployeeID = Value
			End Set
		End Property
		Private m_EmployeeID As Long
		' // not null
		Public Property HireDate() As DateTimeOffset
			Get
				Return m_HireDate
			End Get
			Set
				m_HireDate = Value
			End Set
		End Property
		Private m_HireDate As DateTimeOffset
		' // not null
		Public Property Salary() As Single
			Get
				Return m_Salary
			End Get
			Set
				m_Salary = Value
			End Set
		End Property
		Private m_Salary As Single
		' // not null
	End Class

	<Table("PersonDetails")> _
	Public Class PersonDetail
		Public Property PersonID() As Integer
			Get
				Return m_PersonID
			End Get
			Set
				m_PersonID = Value
			End Set
		End Property
		Private m_PersonID As Integer
		' //PrimaryKey not null
		Public Property Age() As Byte
			Get
				Return m_Age
			End Get
			Set
				m_Age = Value
			End Set
		End Property
		Private m_Age As Byte
		' // not null
		Public Property Gender() As Boolean
			Get
				Return m_Gender
			End Get
			Set
				m_Gender = Value
			End Set
		End Property
		Private m_Gender As Boolean
		' // not null
		Public Property Phone() As String
			Get
				Return m_Phone
			End Get
			Set
				m_Phone = Value
			End Set
		End Property
		Private m_Phone As String
		Public Property Address() As Address
			Get
				Return m_Address
			End Get
			Set
				m_Address = Value
			End Set
		End Property
		Private m_Address As Address
		Public Property Photo() As Stream
			Get
				Return m_Photo
			End Get
			Set
				m_Photo = Value
			End Set
		End Property
		Private m_Photo As Stream
		' // not null
	End Class

	<Table("Advertisements")> _
	Public Class Advertisement
		Public Property ID() As Guid
			Get
				Return m_ID
			End Get
			Set
				m_ID = Value
			End Set
		End Property
		Private m_ID As Guid
		' //PrimaryKey not null
		Public Property Name() As String
			Get
				Return m_Name
			End Get
			Set
				m_Name = Value
			End Set
		End Property
		Private m_Name As String
		Public Property AirDate() As DateTimeOffset
			Get
				Return m_AirDate
			End Get
			Set
				m_AirDate = Value
			End Set
		End Property
		Private m_AirDate As DateTimeOffset
		' // not null
	End Class

End Namespace



'=======================================================
'Service provided by Telerik (www.telerik.com)
'Conversion powered by NRefactory.
'Twitter: @telerik
'Facebook: facebook.com/telerik
'=======================================================
#endif
