//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using  OData2Poco System.
//     Service Url: http://localhost:9091/trippin/v4
//     MetaData Version: 4.0
//     Generated On: 2024-01-20T08:09:17
//     Parameters: 
// 	-o Authenticate= None 
// 	--ssl TlsProtocol= SystemDefault 
// 	-f CodeFilename= poco.cs 
// 	--lang Lang= CS 
// 	-c NameCase= None 
// 	-C EntityNameCase= None 
// 	-G GeneratorType= None 
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.IO;
using System.Collections.Generic;
using Microsoft.Spatial;

namespace Microsoft.OData.SampleService.Models.TripPin
{
	// Complex Entity
	public partial class City
	{
	    public string CountryRegion {get;set;} // not null

	    public string Name {get;set;} // not null

	    public string Region {get;set;} // not null

	}

	// OpenType, Complex Entity
	public partial class Location
	{
	    public string Address {get;set;} // not null

	    public City City {get;set;} 

	}

	// OpenType, Complex Entity
	public partial class EventLocation : Location
	{
	    public string BuildingInfo {get;set;} 

	}

	// OpenType, Complex Entity
	public partial class AirportLocation : Location
	{
	    public GeographyPoint Loc {get;set;} // not null

	}

	// EntitySetName: Photos
	public partial class Photo
	{
	    public long Id {get;} //PrimaryKey not null ReadOnly

	    public string Name {get;set;} 

	}

	// OpenType, EntitySetName: People
	public partial class Person
	{
	    public string UserName {get;} //PrimaryKey not null ReadOnly

	    public string FirstName {get;set;} // not null

	    public string LastName {get;set;} // not null

	    public List<string> Emails {get;set;} 

	    public List<Location> AddressInfo {get;set;} 

	    public PersonGender Gender {get;set;} 

	    public long Concurrency {get;} // not null ReadOnly

	}

	// EntitySetName: Airlines
	public partial class Airline
	{
	    public string AirlineCode {get;} //PrimaryKey not null ReadOnly

	    public string Name {get;set;} // not null

	}

	// EntitySetName: Airports
	public partial class Airport
	{
	    public string IcaoCode {get;} //PrimaryKey not null ReadOnly

	    public string Name {get;set;} // not null

	    public string IataCode {get;set;} // not null

	    public AirportLocation Location {get;set;} 

	}

	// EntitySetName: PlanItem
	public partial class PlanItem
	{
	    public int PlanItemId {get;} //PrimaryKey not null ReadOnly

	    public string ConfirmationCode {get;set;} 

	    public DateTimeOffset StartsAt {get;set;} 

	    public DateTimeOffset EndsAt {get;set;} 

	    public TimeSpan Duration {get;set;} 

	}

	// EntitySetName: PublicTransportation
	public partial class PublicTransportation : PlanItem
	{
	    public string SeatNumber {get;set;} 

	}

	// EntitySetName: Flight
	public partial class Flight : PublicTransportation
	{
	    public string FlightNumber {get;set;} // not null

	}

	// OpenType, EntitySetName: Event
	public partial class Event : PlanItem
	{
	    public string Description {get;set;} 

	    public EventLocation OccursAt {get;set;} 

	}

	// EntitySetName: Trip
	public partial class Trip
	{
	    public int TripId {get;} //PrimaryKey not null ReadOnly

	    public Guid ShareId {get;set;} 

	    public string Description {get;set;} 

	    public string Name {get;set;} // not null

	    public float Budget {get;set;} // not null

	    public DateTimeOffset StartsAt {get;set;} // not null

	    public DateTimeOffset EndsAt {get;set;} // not null

	    public List<string> Tags {get;set;} 

	}

	public enum PersonGender
	 {
 		Male=0,
		Female=1,
		Unknown=2 
	}
}
