//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using  OData2Poco Class library.
//     Service Url: https://services.odata.org/TripPinRESTierService/(S(y3p3ocvb2vzejyij1iyimfh5))
//     MetaData Version: 4.0
//     Generated On: 2019-02-04T23:54:53
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.OData.Service.Sample.TrippinInMemory.Models
{
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
using Microsoft.Spatial;

	[Table("People")]
	public partial class Person
	{
	    [JsonProperty(PropertyName = "UserName")]
	    [Key]
	    [Required]
	    public virtual string UserName {get;set;} //PrimaryKey not null

	    [JsonProperty(PropertyName = "FirstName")]
	    [Required]
	    public virtual string FirstName {get;set;} // not null

	    [JsonProperty(PropertyName = "LastName")]
	    public virtual string LastName {get;set;} 

	    [JsonProperty(PropertyName = "MiddleName")]
	    public virtual string MiddleName {get;set;} 

	    [JsonProperty(PropertyName = "Gender")]
	    [Required]
	    public virtual PersonGender Gender {get;set;} // not null

	    [JsonProperty(PropertyName = "Age")]
	    public virtual long? Age {get;set;} 

	    [JsonProperty(PropertyName = "Emails")]
	    public virtual List<string> Emails {get;set;} 

	    [JsonProperty(PropertyName = "AddressInfo")]
	    public virtual List<Location> AddressInfo {get;set;} 

	    [JsonProperty(PropertyName = "HomeAddress")]
	    public virtual Location HomeAddress {get;set;} 

	    [JsonProperty(PropertyName = "FavoriteFeature")]
	    [Required]
	    public virtual Feature FavoriteFeature {get;set;} // not null

	    [JsonProperty(PropertyName = "Features")]
	    [Required]
	    public virtual List<Feature> Features {get;set;} // not null

	    [JsonProperty(PropertyName = "Friends")]
	    public virtual List<Person> Friends {get;set;} 

	    [JsonProperty(PropertyName = "BestFriend")]
	    public virtual Person BestFriend {get;set;} 

	    [JsonProperty(PropertyName = "Trips")]
	    public virtual List<Trip> Trips {get;set;} 

	}

	[Table("Airlines")]
	public partial class Airline
	{
	    [JsonProperty(PropertyName = "AirlineCode")]
	    [Key]
	    [Required]
	    public virtual string AirlineCode {get;set;} //PrimaryKey not null

	    [JsonProperty(PropertyName = "Name")]
	    public virtual string Name {get;set;} 

	}

	[Table("Airports")]
	public partial class Airport
	{
	    [JsonProperty(PropertyName = "Name")]
	    public virtual string Name {get;set;} 

	    [JsonProperty(PropertyName = "IcaoCode")]
	    [Key]
	    [Required]
	    public virtual string IcaoCode {get;set;} //PrimaryKey not null

	    [JsonProperty(PropertyName = "IataCode")]
	    public virtual string IataCode {get;set;} 

	    [JsonProperty(PropertyName = "Location")]
	    public virtual AirportLocation Location {get;set;} 

	}

	public partial class Location
	{
	    [JsonProperty(PropertyName = "Address")]
	    public virtual string Address {get;set;} 

	    [JsonProperty(PropertyName = "City")]
	    public virtual City City {get;set;} 

	}

	public partial class City
	{
	    [JsonProperty(PropertyName = "Name")]
	    public virtual string Name {get;set;} 

	    [JsonProperty(PropertyName = "CountryRegion")]
	    public virtual string CountryRegion {get;set;} 

	    [JsonProperty(PropertyName = "Region")]
	    public virtual string Region {get;set;} 

	}

	public partial class AirportLocation
	{
	    [JsonProperty(PropertyName = "Loc")]
	    public virtual GeographyPoint Loc {get;set;} 

	}

	public partial class EventLocation
	{
	    [JsonProperty(PropertyName = "BuildingInfo")]
	    public virtual string BuildingInfo {get;set;} 

	}

	public partial class Trip
	{
	    [JsonProperty(PropertyName = "TripId")]
	    [Key]
	    [Required]
	    public virtual int TripId {get;set;} //PrimaryKey not null

	    [JsonProperty(PropertyName = "ShareId")]
	    [Required]
	    public virtual Guid ShareId {get;set;} // not null

	    [JsonProperty(PropertyName = "Name")]
	    public virtual string Name {get;set;} 

	    [JsonProperty(PropertyName = "Budget")]
	    [Required]
	    public virtual float Budget {get;set;} // not null

	    [JsonProperty(PropertyName = "Description")]
	    public virtual string Description {get;set;} 

	    [JsonProperty(PropertyName = "Tags")]
	    public virtual List<string> Tags {get;set;} 

	    [JsonProperty(PropertyName = "StartsAt")]
	    [Required]
	    public virtual DateTimeOffset StartsAt {get;set;} // not null

	    [JsonProperty(PropertyName = "EndsAt")]
	    [Required]
	    public virtual DateTimeOffset EndsAt {get;set;} // not null

	    [JsonProperty(PropertyName = "PlanItems")]
	    public virtual List<PlanItem> PlanItems {get;set;} 

	}

	public partial class PlanItem
	{
	    [JsonProperty(PropertyName = "PlanItemId")]
	    [Key]
	    [Required]
	    public virtual int PlanItemId {get;set;} //PrimaryKey not null

	    [JsonProperty(PropertyName = "ConfirmationCode")]
	    public virtual string ConfirmationCode {get;set;} 

	    [JsonProperty(PropertyName = "StartsAt")]
	    [Required]
	    public virtual DateTimeOffset StartsAt {get;set;} // not null

	    [JsonProperty(PropertyName = "EndsAt")]
	    [Required]
	    public virtual DateTimeOffset EndsAt {get;set;} // not null

	    [JsonProperty(PropertyName = "Duration")]
	    [Required]
	    public virtual TimeSpan Duration {get;set;} // not null

	}

	public partial class Event : PlanItem
	{
	    [JsonProperty(PropertyName = "OccursAt")]
	    public virtual EventLocation OccursAt {get;set;} 

	    [JsonProperty(PropertyName = "Description")]
	    public virtual string Description {get;set;} 

	}

	public partial class PublicTransportation : PlanItem
	{
	    [JsonProperty(PropertyName = "SeatNumber")]
	    public virtual string SeatNumber {get;set;} 

	}

	public partial class Flight : PublicTransportation
	{
	    [JsonProperty(PropertyName = "FlightNumber")]
	    public virtual string FlightNumber {get;set;} 

	    [JsonProperty(PropertyName = "Airline")]
	    public virtual Airline Airline {get;set;} 

	    [JsonProperty(PropertyName = "From")]
	    public virtual Airport From {get;set;} 

	    [JsonProperty(PropertyName = "To")]
	    public virtual Airport To {get;set;} 

	}

	public partial class Employee : Person
	{
	    [JsonProperty(PropertyName = "Cost")]
	    [Required]
	    public virtual long Cost {get;set;} // not null

	    [JsonProperty(PropertyName = "Peers")]
	    public virtual List<Person> Peers {get;set;} 

	}

	public partial class Manager : Person
	{
	    [JsonProperty(PropertyName = "Budget")]
	    [Required]
	    public virtual long Budget {get;set;} // not null

	    [JsonProperty(PropertyName = "BossOffice")]
	    public virtual Location BossOffice {get;set;} 

	    [JsonProperty(PropertyName = "DirectReports")]
	    public virtual List<Person> DirectReports {get;set;} 

	}

	public enum PersonGender
	 {
 		Male=0,
 		Female=1,
 		Unknow=2 
	}
	public enum Feature
	 {
 		Feature1=0,
 		Feature2=1,
 		Feature3=2,
 		Feature4=3 
	}
}
