//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using  OData2Poco System.
//     Service Url: https://myservice.com
//     MetaData Version: 1.0
//     Generated On: 2025-03-08T13:43:08
//     Parameters: 
// 	-u UserName= xyz 
// 	-p Password= ***** 
// 	-o Authenticate= Basic 
// 	- TlsProtocol= SystemDefault 
// 	-f CodeFilename= demo.cs 
// 	- Lang= CS 
// 	-c NameCase= None 
// 	-C EntityNameCase= None 
// 	-G GeneratorType= None 
// </auto-generated>
//------------------------------------------------------------------------------
class Demo
{
}
