// Copyright (c) Mohamed Hassan & Contributors. All rights reserved. See License.md in the project root for license information.

using OData2Poco.TextTransform;

namespace OData2Poco;

public static class CodeHeader
{
    private static List<string> _parameters = new();

    public static string GetHeader(IPocoGenerator pocoGen, bool addArgs = true)
    {
        var comment = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using  OData2Poco System.
//     Service Url: {0}
//     MetaData Version: {1}
//     Generated On: {2}
{3}
// </auto-generated>
//------------------------------------------------------------------------------
";

        //The <auto-generated> tag  at the start of the file
        var h = new FluentCsTextTemplate();
        var pp = _parameters.Where(x => !(x.Trim().StartsWith("-r") || x.Trim().StartsWith("--url")))
            .Select(x => $"// \t{x}");
        h.WriteLine(comment, pocoGen.MetaData.ServiceUrl, pocoGen.MetaData.MetaDataVersion,
            DateTimeOffset.Now.ToString("s"),
            addArgs ? "//     Parameters: \n" + string.Join(Environment.NewLine, pp) : "//");
        return h.ToString();
    }

    public static void SetParameters(List<string> parameters)
    {
        _parameters = new List<string>(parameters);
    }
}