// Copyright (c) Mohamed Hassan & Contributors. All rights reserved. See License.md in the project root for license information.

namespace OData2Poco;

using TextTransform;

public static class CodeHeader
{
    private static List<string> s_parameters = [];

    public static string GetHeader(IPocoGenerator pocoGen, bool addArgs = true)
    {
        _ = pocoGen ?? throw new ArgumentNullException(nameof(pocoGen));
        const string Comment = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using  OData2Poco System.
//     Service Url: {0}
//     MetaData Version: {1}
//     Generated On: {2}
{3}
// </auto-generated>
//------------------------------------------------------------------------------
";

        //The <auto-generated> tag  at the start of the file
        FluentCsTextTemplate h = new();
        var pp = s_parameters.Where(x => !(x.Trim().StartsWith("-r") || x.Trim().StartsWith("--url")))
            .Select(x => $"// \t{x}");
        h.WriteLine(
            Comment,
            pocoGen.MetaData.ServiceUrl,
            pocoGen.MetaData.MetaDataVersion,
            DateTimeOffset.Now.ToString("s"),
            addArgs ? "//     Parameters: \n" + string.Join(Environment.NewLine, pp) : "//");
        return h.ToString();
    }

    public static void SetParameters(List<string> parameters)
    {
        s_parameters = [.. parameters];
    }
}
