using OData2Poco.TextTransform;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;

namespace OData2Poco
{
    public class CodeHeader
    {
        static List<string> Parameters = new List<string>();
        public static string GetHeader(IPocoGenerator pocoGen,bool addArgs=true)
        {
            var comment = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using  OData2Poco System.
//     Service Url: {0}
//     MetaData Version: {1}
//     Generated On: {2}
{3}
// </auto-generated>
//------------------------------------------------------------------------------
";

            //The <auto-generated> tag  at the start of the file
            var h = new FluentCsTextTemplate();
            var pp = Parameters.Where(x => !(x.Trim().StartsWith("-r") || x.Trim().StartsWith("--url")))
                .Select(x => $"// \t{x}");
            h.WriteLine(comment, pocoGen.MetaData.ServiceUrl, pocoGen.MetaData.MetaDataVersion,
                DateTimeOffset.Now.ToString("s"), 
              addArgs? "//     Parameters: \n" + string.Join(Environment.NewLine, pp):"//");
            return h.ToString();
        }
        public static void SetParameters(List<string> parameters)
        {
            Parameters = new List<string>(parameters);
        }
    }
}
